version: 2.1
jobs:
  build:
    docker:
        - image: php:7.2-apache
        - image: mysql:5.7
    working_directory: ~/app
    steps:
        - checkout
        - run:
            name: undo-bbs
            command: 'docker-compose up -d'