version: 2.1

jobs:
  build:
    docker:
        - image: php:7.2-apache
          environment:
            - APP_DEFAULT_LOCALE=ja_JP
            - APP_DEFAULT_TIMEZONE=Asia/Tokyo
        - image: circleci/mysql:5.7
          environment:
            - DATABASE_HOST=undo-bbs-db
            - DATABASE_USER=root
            - DATABASE_PASS=root
            - DATABASE_NAME=qc_app
            - DATABASE_TEST_URL=mysql://root:secret@undo-bbs-db/test

commands:
  steps:
    - checkout
    - run:
      name: setup
      command: bash -c "sh docker-init-setup.sh && apache2-foreground"