version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
        - image: php:7.2-apache
        - image: circleci/mysql:5.7
          environment: 
            MYSQL_DATABASE: "qc_app"
            MYSQL_ROOT_PASSWORD: "root"
    steps:
        - checkout
        - run:
          command: docker-compose up -d