version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: bash -c "sh docker-init-setup.sh && apache2-foreground"
  test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test